apiVersion: v1
kind: Secret
metadata:
  name: coldmart-secrets
  namespace: coldmart
type: Opaque
stringData:
  db-password: "Strong@Passw0rd"
  rabbitmq-user: "coldmart"
  rabbitmq-password: "coldmart"
  jwt-signing-key: "V6lNvSvWgiXk8V0yfzml3QlR8SNy6xtW"
  auth-connection-string: "Server=coldmart-db,1433;Database=AuthColdmart;TrustServerCertificate=True;User Id=sa;Password=Strong@Passw0rd"
  cursos-connection-string: "Server=coldmart-db,1433;Database=CursosColdmart;TrustServerCertificate=True;User Id=sa;Password=Strong@Passw0rd"
  alunos-connection-string: "Server=coldmart-db,1433;Database=AlunoColdmart;TrustServerCertificate=True;User Id=sa;Password=Strong@Passw0rd"
  pagamentos-connection-string: "Server=coldmart-db,1433;Database=PagamentosColdmart;TrustServerCertificate=True;User Id=sa;Password=Strong@Passw0rd"
