apiVersion: v1
kind: Secret
metadata:
  name: coldmart-secrets
  namespace: coldmart
type: Opaque
stringData:
  db-password: "Strong@Passw0rd"
  rabbitmq-user: "coldmart"
  rabbitmq-password: "coldmart"
  jwt-signing-key: "V6lNvSvWgiXk8V0yfzml3QlR8SNy6xtW"
