SET ANSI_NULLS ON
GO

SET QUOTED_IDENTIFIER ON
GO

IF NOT EXISTS (SELECT name FROM sys.databases WHERE name = N'CursoColdmart')
BEGIN
    CREATE DATABASE [CursoColdmart] WITH CATALOG_COLLATION = SQL_Latin1_General_CP1_CI_AS, LEDGER = OFF;
END
GO

IF NOT EXISTS (SELECT name FROM sys.databases WHERE name = N'PagamentoColdmart')
BEGIN
    CREATE DATABASE [PagamentoColdmart] WITH CATALOG_COLLATION = SQL_Latin1_General_CP1_CI_AS, LEDGER = OFF;
END
GO

IF NOT EXISTS (SELECT name FROM sys.databases WHERE name = N'AuthColdmart')
BEGIN
    CREATE DATABASE [AuthColdmart] WITH CATALOG_COLLATION = SQL_Latin1_General_CP1_CI_AS, LEDGER = OFF;
END
GO

IF NOT EXISTS (SELECT name FROM sys.databases WHERE name = N'AlunoColdmart')
BEGIN
    CREATE DATABASE [AlunoColdmart] WITH CATALOG_COLLATION = SQL_Latin1_General_CP1_CI_AS, LEDGER = OFF;
END
GO