name: Build Pagamentos API

permissions:
  contents: write
  pull-requests: write
  actions: read
  packages: read
  security-events: write

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  call-reusable:
    uses: ./.github/workflows/build-base.yml
    with:
      project: "Pagamentos.API"
      image: "pagamentos"
    secrets: inherit
