name: Build Cursos API

permissions:
  contents: write

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  call-reusable:
    uses: ./.github/workflows/build-base.yml
    with:
      project: "Cursos.API"
      image: "cursos"
