name: Build Auth API

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

  workflow_dispatch:

jobs:
  call-reusable:
    uses: ./.github/workflows/build-base.yml
    with:
      project: "Auth.API"
      image: "auth"
