name: Build BFF

permissions:
  contents: write
  pull-requests: write
  actions: read
  packages: read
  security-events: write

on:
  push:
    branches:
      - main
    paths:
      - '.github/workflows/build-bff.yml'
      - '.github/workflows/build-base.yml'
      - 'Coldmart.sln'
      - 'src/Coldmart.BFF/**'
      - 'src/Coldmart.Core/**'
      - 'tests/Coldmart.BFF.Tests/**'
      - 'tests/Coldmart.Core.Tests/**'
  pull_request:
    branches:
      - main
    paths:
      - '.github/workflows/build-bff.yml'
      - '.github/workflows/build-base.yml'
      - 'Coldmart.sln'
      - 'src/Coldmart.BFF/**'
      - 'src/Coldmart.Core/**'
      - 'tests/Coldmart.BFF.Tests/**'
      - 'tests/Coldmart.Core.Tests/**'
  workflow_dispatch:

jobs:
  call-reusable:
    uses: ./.github/workflows/build-base.yml
    with:
      project: "BFF"
      image: "bff"
    secrets: inherit
